import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "chilli-masala",
    name: "Chilli Masala",
    description: "Extra spicy, vibrant red chilli powder sourced from Guntur farms.",
    price: 120,
    image: "/input_file_1.png",
    category: "Basic",
  },
  {
    id: "turmeric-masala",
    name: "Turmeric Masala",
    description: "Pure, high-curcumin turmeric for health and authentic color.",
    price: 90,
    image: "/input_file_5.png",
    category: "Basic",
  },
  {
    id: "ginger-masala",
    name: "Ginger Powder",
    description: "Zesty and aromatic ginger powder for that perfect punch.",
    price: 150,
    image: "https://picsum.photos/seed/ginger-spice/600/400",
    category: "Basic",
  },
  {
    id: "coriander-powder",
    name: "Coriander Powder",
    description: "Freshly ground coriander seeds for a mild, earthy aroma.",
    price: 110,
    image: "/input_file_2.png",
    category: "Basic",
  },
  {
    id: "garam-masala",
    name: "Garam Masala",
    description: "A secret blend of whole spices for a rich, royal aroma.",
    price: 180,
    image: "/input_file_3.png",
    category: "Masala",
  },
  {
    id: "curry-masala",
    name: "Curry Masala",
    description: "The soul of Andhra curries, balanced and flavorful.",
    price: 140,
    image: "https://picsum.photos/seed/curry-spice/600/400",
    category: "Masala",
  },
  {
    id: "sambar-masala",
    name: "Sambar Masala",
    description: "Tangy and spicy blend for the perfect South Indian Sambar.",
    price: 130,
    image: "https://picsum.photos/seed/sambar-spice/600/400",
    category: "Masala",
  },
  {
    id: "chicken-masala",
    name: "Chicken Masala",
    description: "Specially crafted for juicy, spicy Andhra-style chicken fry.",
    price: 160,
    image: "/input_file_0.png",
    category: "Non-Veg",
  },
  {
    id: "meat-masala",
    name: "Meat Masala",
    description: "Robust and deep flavors for slow-cooked meat delicacies.",
    price: 190,
    image: "/input_file_4.png",
    category: "Non-Veg",
  },
];
